version: 2
jobs:
  build:
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    docker:
    - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      # Set things up
      - checkout

      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            sudo apt install libxmlsec1-dev

      - run:
          name: install squaresdb
          command: |
            . venv/bin/activate
            pip install .

      - run:
          name: dev setup
          command: |
            . venv/bin/activate
            squaresdb/utils/install.py --email testing@mit.edu

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ./manage.py check
            python manage.py test


      # Store outputs
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
