- name: Install packages
  ansible.builtin.package:
      name:
        # Ansible
        - python3-pymysql
        - python3-virtualenv
        # Python build-deps
        - gcc
        - python3-dev
        - libxmlsec1-dev
        - pkg-config
        - libmysqlclient-dev
        # Hosting
        - libapache2-mod-wsgi-py3
        # JS local libraries
        - libjs-bootstrap4
        - libjs-popper.js
      state: present

# Unix account
- name: Create Unix group
  ansible.builtin.group:
      name: squaresdb

- name: Create Unix user
  ansible.builtin.user:
      name: squaresdb
      group: squaresdb
      comment: SquaresDB
      password: '!'
      home: /home/squaresdb


# Database

# Assumes mysql is preinstalled, with the socket pluggable auth mechanism
# setup -- see
# https://dev.mysql.com/doc/refman/8.0/en/socket-pluggable-authentication.html
# Also assumes timezones are loaded already:
# https://docs.djangoproject.com/en/4.0/ref/databases/#mysql-time-zone-definitions
# https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html

- name: Create MySQL DB
  community.mysql.mysql_db:
      name: squaresdb
      state: present
      encoding: utf8
      collation: utf8_general_ci

- name: Create MySQL user
  community.mysql.mysql_user:
      name: squaresdb
      state: present
      plugin: auth_socket
      priv:
          'squaresdb.*': 'ALTER,CREATE,DELETE,DROP,INDEX,INSERT,REFERENCES,SELECT,UPDATE'

# SquaresDB code
- name: Install virtualenv
  ansible.builtin.pip:
      name:
          - git+https://github.com/dehnert/social-core.git@snap/names-settings#egg=social-auth-core[saml]
          - git+https://github.com/tech-squares/squaresdb.git@socialauth#egg=squaresdb[mysql]
      editable: true
      virtualenv: /home/squaresdb/venv
      virtualenv_python: python3
  become: yes
  become_user: squaresdb
  notify:
      - Reload apache

# TODO: Better settings. Need to configure MySQL
# TODO: Import membership DB?
# TODO: create superuser account?

- name: Add Django SECRET_KEY if missing
  ansible.builtin.copy:
      dest: /home/squaresdb/venv/src/squaresdb/squaresdb/settings/django_secret_key.txt
      owner: squaresdb
      mode: 0600
      content: "{{lookup('community.general.random_string', special=false, length=50)}}"
      force: no
  notify:
      - Reload apache

- name: Copy external auth secrets
  ansible.builtin.copy:
      src: roles/squaresdb/files/{{item}}
      dest: /home/squaresdb/venv/src/squaresdb/squaresdb/settings/{{item}}
      owner: squaresdb
      mode: 0600
      decrypt: yes
  loop:
      - google-oauth.json
      - saml.key
      # Not secret, so not encrypted; Ansible handles this automatically
      - saml.crt
  notify:
      - Reload apache

- name: Configure Django
  ansible.builtin.template:
      src: "roles/squaresdb/templates/django_local.py.j2"
      dest: /home/squaresdb/venv/src/squaresdb/squaresdb/settings/local.py
  notify:
      - Reload apache

- name: Django - Migrate DB
  ansible.builtin.command:
      cmd: ../../bin/django-admin migrate
      chdir: /home/squaresdb/venv/src/squaresdb/
  environment:
      DJANGO_SETTINGS_MODULE: squaresdb.settings
  become: yes
  become_user: squaresdb
  register: django_migrate_out
- debug:
      var: django_migrate_out.stdout_lines

- name: Django - createinitialrevisions
  ansible.builtin.command:
      cmd: ../../bin/django-admin createinitialrevisions --comment="Initial revision (in Ansible)" membership
      chdir: /home/squaresdb/venv/src/squaresdb/
  environment:
      DJANGO_SETTINGS_MODULE: squaresdb.settings
  become: yes
  become_user: squaresdb
  register: django_createinitialrevisions_out
- debug:
      var: django_createinitialrevisions_out.stdout_lines

- name: create vhost directory for static files
  ansible.builtin.file:
      name: /var/www/squaresdb/
      state: directory
      owner: squaresdb
      mode: 0755

- name: Collect static files
  ansible.builtin.command:
      cmd: ../../bin/python ./manage.py collectstatic --link
      chdir: /home/squaresdb/venv/src/squaresdb/
      creates: /var/www/squaresdb/static/admin/
  become: yes
  become_user: squaresdb


# Web server
# This uses the photos vhost, but that's fine
- name: Fetch cert
  ansible.builtin.command:
      cmd: certbot --non-interactive --agree-tos -m squares-db@mit.edu certonly --webroot --webroot-path=/var/www/html/ -d {{extname}} {%for name in vhost_aliases%} -d {{name}}{%endfor%}
      creates: /etc/letsencrypt/live/{{extname}}/

- name: Configure Apache2 vhosts
  ansible.builtin.template:
      src: "roles/squaresdb/templates/vhost.conf"
      dest: "/etc/apache2/sites-available/squaresdb.conf"
  notify:
      - Reload apache

- name: Enable Apache2 Machine vhost
  ansible.builtin.file:
      state: link
      src: ../sites-available/squaresdb.conf
      dest: /etc/apache2/sites-enabled/squaresdb.conf
  notify:
      - Reload apache
